export const jobs = [
    {
      name: "software-engineer",
      role: "Software Engineer",
      company: "TechNova Inc.",
      logoUrl: "/images/technova-logo.png", // place your logo in public/images
      description: `Developed cutting-edge web applications and collaborated with cross-functional teams to integrate new features. Focused on building efficient, maintainable code.`,
      startDate: "Jan 2022",
      endDate: "Dec 2022",
    },
    {
      name: "product-manager",
      role: "Product Manager",
      company: "Visionary Labs",
      logoUrl: "/images/visionary-labs-logo.png",
      description: `Led a high-impact team that launched two major product lines. Utilized data-driven insights to refine product vision and roadmap.`,
      startDate: "Jan 2021",
      endDate: "Dec 2021",
    },
    {
      name: "frontend-developer",
      role: "Frontend Developer",
      company: "Digital Horizons",
      logoUrl: "/images/digital-horizons-logo.png",
      description: `Designed and implemented responsive user interfaces for enterprise clients. Optimized web performance and accessibility across multiple platforms and devices.`,
      startDate: "Mar 2020",
      endDate: "Dec 2020",
    },
    {
      name: "teaching-assistant",
      role: "Teaching Assistant",
      company: "Utah State University",
      logoUrl: "/images/usu-logo.png",
      description: `Assisted professors in teaching fundamental computer science concepts. Led lab sessions, graded assignments, and provided one-on-one tutoring for students struggling with data structures and algorithms.`,
      startDate: "Aug 2019",
      endDate: "May 2020",
    },
    {
      name: "software-intern",
      role: "Software Development Intern",
      company: "CloudSphere Solutions",
      logoUrl: "/images/cloudsphere-logo.png",
      description: `Contributed to backend services using Python and AWS. Participated in agile development processes and gained hands-on experience with CI/CD pipelines and cloud infrastructure.`,
      startDate: "May 2019",
      endDate: "Aug 2019",
    },
  ]
  
  export const projects = [
    {
      name: "galaxy-explorer",
      title: "Galaxy Explorer",
      imageUrl: "/images/galaxy-explorer.png",
      description: `A 3D visualization tool that allows users to explore galaxies in real time. Includes advanced search features and custom planet generation.`,
      technologies: ["Three.js", "React", "Node.js"],
      startDate: "Jun 2022",
      endDate: "Sep 2022",
    },
    {
      name: "smart-home-app",
      title: "Smart Home Controller",
      imageUrl: "/images/smart-home.png",
      description: `A mobile-friendly application to manage and monitor IoT devices throughout a house, featuring real-time data analysis and alerts.`,
      technologies: ["Next.js", "Tailwind CSS", "Firebase"],
      startDate: "Oct 2022",
      endDate: "Jan 2023",
    },
    {
      name: "data-dashboard",
      title: "Interactive Data Dashboard",
      imageUrl: "/images/data-dashboard.png",
      description: `A comprehensive analytics platform that transforms complex datasets into intuitive visualizations. Features customizable charts, real-time updates, and exportable reports.`,
      technologies: ["D3.js", "TypeScript", "Express", "MongoDB"],
      startDate: "Feb 2023",
      endDate: "May 2023",
    },
    {
      name: "fitness-tracker",
      title: "FitTrack Mobile App",
      imageUrl: "/images/fittrack.png",
      description: `A cross-platform mobile application for tracking workouts, nutrition, and health metrics. Includes social features for connecting with friends and participating in challenges.`,
      technologies: ["React Native", "Redux", "Firebase", "HealthKit API"],
      startDate: "Jun 2023",
      endDate: "Sep 2023",
    },
    {
      name: "sentiment-analyzer",
      title: "Social Media Sentiment Analyzer",
      imageUrl: "/images/sentiment-analyzer.png",
      description: `A machine learning tool that analyzes social media posts to determine public sentiment about brands or topics. Provides trend analysis and actionable insights for marketing teams.`,
      technologies: ["Python", "TensorFlow", "Natural Language Processing", "Flask"],
      startDate: "Oct 2023",
      endDate: "Present",
    },
  ]